name: build_openlist

on:
  # 支持手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
          cache-dependency-path: ${{ github.workspace }}/AListLib/go.sum

      - name: checkout_code
        uses: actions/checkout@v3

      - name: Install gomobile and initialize
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          # 切换到AListLib目录，因为gomobile init可能需要在项目的根目录或Go模块目录下执行
          cd $GITHUB_WORKSPACE/AListLib
          gomobile init
          # 返回脚本目录，以便执行后续的构建脚本
          cd $GITHUB_WORKSPACE/AListLib/scripts

      - name: build openlist aar
        run: |
          cd $GITHUB_WORKSPACE/AListLib/scripts
          sh install_alist.sh
          sh build_aar.sh
          cp -f $GITHUB_WORKSPACE/AListLib/sources/alistlib.aar $GITHUB_WORKSPACE/app/libs
