name: build_openlist

on:
  # 支持手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
          cache-dependency-path: ${{ github.workspace }}/AListLib/go.sum

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          # 将 go bin 目录添加到 PATH，确保后续步骤能找到 gomobile
          echo "$(go env GOBIN)" >> $GITHUB_PATH
          gomobile init

      - name: Download OpenList source and frontend
        run: |
          # 确保目标目录存在
          mkdir -p ${{ github.workspace }}/AListLib/sources
          
          # 获取最新的 OpenList tag
          TAG_NAME=$(curl -s https://api.github.com/repos/OpenListTeam/OpenList/releases/latest | grep -o '"tag_name": ".*"' | cut -d'"' -f4)
          echo "Latest OpenList tag is ${TAG_NAME}"

          # 下载 OpenList 后端源码
          BACKEND_URL="https://github.com/OpenListTeam/OpenList/archive/refs/tags/${TAG_NAME}.tar.gz"
          echo "Downloading OpenList source from ${BACKEND_URL}"
          curl -L "${BACKEND_URL}" | tar xz --strip-components=1 -C "${{ github.workspace }}/AListLib/sources"

          # 下载 OpenList 前端
          FRONTEND_URL="https://github.com/OpenListTeam/OpenList-Frontend/releases/latest/download/openlist-frontend-dist-${TAG_NAME}.tar.gz"
          echo "Downloading OpenList frontend from ${FRONTEND_URL}"
          mkdir -p "${{ github.workspace }}/AListLib/sources/public/dist"
          curl -L "${FRONTEND_URL}" | tar xz -C "${{ github.workspace }}/AListLib/sources/public/dist"

      - name: Build alistlib.aar
        # 设置工作目录到 Go 项目的根目录
        working-directory: ${{ github.workspace }}/AListLib/sources
        run: |
          echo "Fetching Go module dependencies..."
          # 下载依赖
          go mod tidy
          
          echo "Building alistlib.aar..."
          # 执行构建
          gomobile bind -ldflags="-s -w" -v -androidapi 21 "github.com/OpenListTeam/OpenList/v4/alistlib"
          
          # 检查 AAR 文件是否成功生成
          if [ ! -f "alistlib.aar" ]; then
            echo "::error::Failed to build alistlib.aar. The file was not found after the build command."
            exit 1
          fi
          
          echo "alistlib.aar built successfully."

      - name: Copy AAR to app libs
        run: |
          mkdir -p ${{ github.workspace }}/app/libs
          cp -f ${{ github.workspace }}/AListLib/sources/alistlib.aar ${{ github.workspace }}/app/libs/
          echo "alistlib.aar copied to app/libs"

      - name: Set personalized config (Optional)
        run: |
          echo "This step can be used to set the versions in your Android app source files."
          # 您可以在这里放置更新版本号的 sed 命令
          # 例如:
          # TAG_NAME=$(curl -s https://api.github.com/repos/OpenListTeam/OpenList/releases/latest | grep -o '"tag_name": ".*"' | cut -d'"' -f4)
          # sed -i "s/\(public static String OPENLIST_VERSION = \"\)\([^\";]*\)\(\";\)/\1${TAG_NAME}\3/" ${{ github.workspace }}/app/src/main/java/com/leohao/android/alistlite/util/Constants.java

