name: sync_latest_alist

on:
  # 支持手动触发
  workflow_dispatch:
  # 每小时执行一次
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check_alist_version
      - run: |
          export CURRENT_ALIST_VERSION="$(sed -n 's/.*ALIST_VERSION = "\([^"]*\)".*/\1/p' Constants.java)"
          echo "CURRENT_ALIST_VERSION: " ${CURRENT_ALIST_VERSION}
